server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}/

  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa